Consistently use gfm rather than markdown_github
inbo/tutorials pull request #285
Opened 2021-11-17 15:59 UTC by peterdesmet

## Description

Some `index.Rmd` files used the deprecated `variant: markdown_github`, which results in a warning when knitting. This PR updates all `index.Rmd` files to consistently use the recommended `gfm` and 2-space indentation in yaml frontmatter:

```
output: 
  md_document:
    preserve_yaml: true
    variant: gfm
```

For some tutorials, this updates the `index_files/figure-markdown_github` to `index_files/gfm`. The PR has little to no effect on the website.

2021-12-07 14:14 UTC, florisvdh requested changes
All seems fine, except in one Rmd file where some characters were escaped for an unknown reason. I suggest to revert that since it is not consistent with Pandoc's markdown.

2021-12-07 14:14 UTC, florisvdh commented on content/tutorials/r_citations_markdown/index.Rmd
> +### Other YAML citation arguments {\#other-yaml-citation-arguments}
I suggest to revert this change, it doesn't follow the recommended markdown syntax.

2021-12-07 14:14 UTC, florisvdh commented on content/tutorials/r_citations_markdown/index.Rmd
> +# Citing documents {\#citing-documents}
I suggest to revert this change, it doesn't follow the recommended markdown syntax.

2021-12-07 14:14 UTC, florisvdh commented on content/tutorials/r_citations_markdown/index.Rmd
> +| delineate multiple authors with colon: `[@adams1975; @aberdeen1958]` | delineate multiple authors with colon: \[\@adams1975; \@aberdeen1958\] |
Please revert this change, it doesn't follow the recommended markdown syntax.

2021-12-07 14:14 UTC, florisvdh commented on content/tutorials/r_citations_markdown/index.Rmd
> +... allows us to cite \@R-base, \@R-bookdown and \@R-rmarkdown if we add `packages.bib` to the bibliography YAML field.
Please revert this change, it doesn't follow the recommended markdown syntax.

2021-12-07 15:02 UTC, florisvdh reviewed
Further, see https://github.com/inbo/tutorials/issues/200#issuecomment-988006466. I advise to use `gfm+footnotes` instead of `gfm`.

Thanks for the efforts you have been doing here @peterdesmet :+1:

2021-12-07 15:09 UTC, florisvdh commented
> I advise to use `gfm+footnotes` instead of `gfm`.

In order not to have to re-knit tutorials, you could just update the Rmd files here, so that this is taken care of next time they are knitted. But probably that is your approach already.

Caveat: some open pull requests contain new tutorials, so the changes may have to be applied there as well.

2022-01-27 08:24 UTC, florisvdh commented
> Caveat: some open pull requests contain new tutorials, so the changes may have to be applied there as well.

In order to limit this problem, can you have a further look at remaining tasks in this PR @peterdesmet, so that we get this in `master`? Thanks!

2022-01-27 17:03 UTC, peterdesmet commented
@florisvdh the backslashes are removed. Do you want me to use `gfm+footnotes` everywhere or in specific places?

2022-01-27 17:26 UTC, florisvdh commented
> @florisvdh the backslashes are removed. Do you want me to use `gfm+footnotes` everywhere or in specific places?

I suggest to do it everywhere, since often a new tutorial will be based on another one and we better do it consistently. If you wish, I could try to do this at once, with `sed`. Further, such update is best applied to existing PRs with new tutorials, not only `master`. Maybe the 'create tutorial' tutorial also needs checking.

If you'd find a way to let Hugo make the citation links that appear useful - i.e. the links which appear after adding `link-citations: true` - then that would be superb! I didn't find the solution in https://github.com/inbo/tutorials/issues/200#issuecomment-988006466.

2022-01-28 15:40 UTC, peterdesmet commented
@florisvdh I have
- Removed `output` frontmatter from `index.md` files that are not generated from `index.Rmd`
- Updated `index.Rmd` frontmatter to use `gfm+footnotes` and knitted where relevant. See e.g. footnotes at bottom, where they weren't there before at https://inbo.github.io/tutorials/tutorials/spatial_crs_coding/
- Updated `create a tutorial` to indicate the desired frontmatter

2022-01-28 15:43 UTC, peterdesmet commented
And finally, I have updated the frontmatter in the open pull requests, so we don't reintroduce old frontmatter.

2022-01-31 08:10 UTC, florisvdh approved these changes
Perfect, well done :+1: . Thank you!

2022-01-31 08:10 UTC, merged